# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# In CircleCI configuration file, the version field specifies the version of the configuration file syntax that is being used. The version field is the first line of the configuration file and it is required in order for CircleCI to properly interpret the configuration file.
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image:node:18.10.0

    steps:
      - checkout
      - run: npm install
      - run: npm test
